### ISSUE TITLE
Making changes and Pull requests

### ISSUE THREAD

**Issue by MesutBE** [MesutBE/Driving-Licence-App#12]
Hi team,

I have always nonsense conflicts when I trying to pull from main repo.

My suggestion is if anybody makes a change in the repository do not make merge. Only make a pull request and all the team members can see the difference and maybe give an idea on it. And after that we can merge it. At this time they are silly conflicts because they are new line and deleted line like conflicts. But one week later there may be some big conflicts. So the most effective way to avoid that problem merging it after our pull requests are reviewed by other team members.

Do you have any idea about that?

**Comment by feridunAKYOL** [comment]
I agree with you...
one , for our project you , should manage the repo..this way is more easy..

**Comment by ayseakyol** [comment]
Good morning, It is a good idea.. We can do only pull requests.
