### ISSUE TITLE
12. User Story: Test Page

### ISSUE THREAD

**Issue by MesutBE** [MesutBE/Driving-Licence-App#19]
- Initialization
   - Create one method/function to read from db on `situation` table `text`, `image`, `audio` columns test-related situation.
  and on `question` table `text`, `audio` columns situation-related question. _and  `correct count` from `result` table. (because in the test page he will see tests with a image and at the bottom the result if he solve the test before)_ 
- After click `End My Test`
  - Create one method/function to read from db on `situation` table `image` columns test-related situation.
  and on `option` table `correctOption` columns question-related option to make see which questions are correct which are wrong.
- _create a function to write the success percentage (correct count / total question) to the db on `result` table._
  
- Results 
  - Create one method/function to write to db on `result` table `correctCount` columns which relates chosen test.

**Comment by feridunAKYOL** [comment]
I have add some edition above with italic style...
