### ISSUE TITLE
User-Stories

### ISSUE THREAD

**Issue by thomashaile** [MesutBE/Driving-Licence-App#2]
1. Objective of our system
Standardize and automate the procedure of evaluating the driving skills of a driver
Eliminate subjective opinion of an examiner
Same procedure will assess every candidate
2. Advantage of our system
no subjectivity
no multiple examiners
transparency
ensure selection based on merit
3. user stories
3.1 User(candidate or driver)
user can register online (self-registration)
user can login
user can recover/reset his password
user can get reading materials/resources
user can take driving practice test
user can apply for theory test online
user can get his candidate number to take the online test
user can take online theory test
user can view his result afetr he complete the test
user can see the soulution/corrections
user can take re-exam(re-test)
user can post comment, question, feedback
3.2 Test - Examiner (Expert)
Expert can login to his home page
Expert can add/update/delete exam
Expert can add/update/delete questions
 Expert can add/update/delete answers
 Expert can view test results
3.3 Admin (Super admin)
admin can add/update/delete user accounts
 admin can assign role to user
admin can add resource materials
admin can see results

**Comment by MesutBE** [comment]
I added user stories to dev-str. First and second topic we can use them in the readme file to.. Thx @thomashaile
