### ISSUE TITLE
2. Create wireframes

### ISSUE THREAD

**Issue by MesutBE** [MesutBE/Driving-Licence-App#5]
2. Create wireframes (if it is possible until tomorrow evening)
I think only one person can create wireframes if anybody wants to add something it can be updated.

   - [x] **Default home page wire frame**  https://wireframe.cc/f2K1UO
   - [x] **Signup page wireframe.**  https://wireframe.cc/eV0U0h
   - [x] **Signin/login page wireframe** https://wireframe.cc/Q8E1ar
   - [x] **Forget Password**  https://wireframe.cc/aqQIqI
   - [x] **Registerd user homepage**  https://wireframe.cc/mgj0mx
   - [x] **Registered admin/expert homepage** https://wireframe.cc/uuyjz1

**Comment by thomashaile** [comment]
i can create this one..

**Comment by MesutBE** [comment]
ok it is yours @thomashaile

**Comment by feridunAKYOL** [comment]
> i can create this one..

@thomashaile but I think there is not only `ONE` :sweat_smile:

**Comment by thomashaile** [comment]
1. Default home page wire frame https://wireframe.cc/f2K1UO
2. signup page wireframe. https://wireframe.cc/eV0U0h
3. signin/login page wireframe https://wireframe.cc/Q8E1ar
4. Forget Password https://wireframe.cc/aqQIqI
5. registerd user homepage  https://wireframe.cc/mgj0mx
6. registered admin/expert homepage  https://wireframe.cc/uuyjz1

**Comment by thomashaile** [comment]
> > i can create this one..
> 
> @thomashaile but I think there is not only `ONE` 😅

yes ferudin ... you can help me 👍

**Comment by feridunAKYOL** [comment]
@thomashaile what do you mean by `theory online exam` ?
- if it is what I think , our app will be only preparation to the real exam by small quizzes.(20 question in each quiz) 
- if we think to prepare a sample exam , this is another task maybe?(but should be optional)

**Comment by feridunAKYOL** [comment]
by the way we can help if you need?

**Comment by thomashaile** [comment]
What i want to say the exam is only theory part?  Right,  it doesnt enclude
z practical part. Or...?

**Comment by thomashaile** [comment]
What i understand is The practice exam is optional(we will do this if we
have time). But the users can take the real written exam(which is the
theory part). do i understand wrongly?

**Comment by feridunAKYOL** [comment]
actually I don't think so...
not a real written exam but a partial exam..
for example there are many subjects.. and student study for each part..

**Comment by thomashaile** [comment]
if so, what is the use of our application? i thought they can read tutorials, can also take practice test(optional-also maybe we dont need to use db for this)., and then they can take the theory written exam online.  this was what i understant

**Comment by feridunAKYOL** [comment]
just think about like that..
we are preparing for web development exam..
and in our application there are many separate course.. one of them is about functions.. the other test is about bootstrap etc...
but in the exam we get questions from all part

**Comment by feridunAKYOL** [comment]
do you mean official theory test or a sample test?

**Comment by thomashaile** [comment]
yes... but still it is theory part. they dont need to show us in practical and we dont know if they can drive. also they need to pass each exam like i said.

**Comment by thomashaile** [comment]
official test but we can have 1,2,3 test.  we can use sample test for the practice test.

**Comment by Rahela-HYF** [comment]
4. Forget Password https://wireframe.cc/aqQIqI

**Comment by thomashaile** [comment]
ferudin you can also look at the database relation table. 1 user can take many exams.

**Comment by MesutBE** [comment]
For my opinion, we need to focus on making an training app, user can make practice for his official exams.

**Comment by thomashaile** [comment]
if so, for the training app we don't need to use any database.

**Comment by MesutBE** [comment]
>        * [x]  **Default home page wire frame**  https://wireframe.cc/f2K1UO
For home page, I think we can focus on navbar, footer. I think a driving license course don't have an option to make an official exam so "Pass your official Theory test" section can be deleted. And then we need to make more sections in the main section. For example news about regulations, Official exam dates announced by the government, 
>        * [x]  **Signup page wireframe.**  https://wireframe.cc/eV0U0h
I think the users which signup this website are already a student of a school or they are another quests, so we can collect less information. If they are already from a school, the school has already their all the information.
Citizenship can be Country, Address: not necessary, 
I don't understand  "picture"
And the button names should copy the same as google signup pages and the other big ones.
>        * [x]  **Signin/login page wireframe** https://wireframe.cc/Q8E1ar
I like this page a lot, clean simple.. 
>        * [x]  **Forget Password**  https://wireframe.cc/aqQIqI
In this page I think we need 2 UI, first of all asking Question, if it is excepted then ask for new password.
>        * [x]  **Registerd user homepage**  https://wireframe.cc/mgj0mx
>        * [x]  **Registered admin/expert homepage** https://wireframe.cc/uuyjz1
I want to make a name change admin/expert to teacher?
We can let teacher managing questions as license type by sorting questions in a simple usable table. So no need a license type button 
Change suggestion => "Manage users" to "User Results" because I think a teacher can only make a suggestion to a user re-test.


**What do you think @ayseakyol @Rahela-HYF @feridunAKYOL @OmerSnck @thomashaile?**

**Comment by MesutBE** [comment]
> if so, for the training app we don't need to use any database.

@thomashaile I don't agree with you, for this app we hardly need a database. 
How can we manage, 
users, their infos, tests that taken, online/offline status, their results
on the other hand questions, answers
and relationship between eachother?
If you say with JSON. I think it will be get confusing. 

Let's talk that [here](https://github.com/MesutBE/Driving-Licence-App/issues/6).
