### ISSUE TITLE
3. Database Schema

### ISSUE THREAD

**Issue by MesutBE** [MesutBE/Driving-Licence-App#6]
3. Database.
Please comment below if you watch the video which Feridun sent, In the video you will see some differences between MongoDB and sqlite like databases, so do you think which one is fit for our project? After your comments we can finalize our DB.

**Comment by thomashaile** [comment]
sqllite is better will be easier at this time

**Comment by thomashaile** [comment]
https://www.youtube.com/watch?v=HPIjjFGYSJ4 -react, nodejs, with mysql db
https://www.youtube.com/watch?v=4CeTFW4agRw.  -react form validation

**Comment by thomashaile** [comment]
1. Default home page wire frame https://wireframe.cc/f2K1UO
2. signup page wireframe. https://wireframe.cc/eV0U0h
3. signin/login page wireframe
4. registerd user homepage
5. registered admin/expert homepage

**Comment by MesutBE** [comment]
>     1. Default home page wire frame https://wireframe.cc/f2K1UO
> 
>     2. signup page wireframe. https://wireframe.cc/eV0U0h
> 
>     3. signin/login page wireframe
> 
>     4. registerd user homepage
> 
>     5. registered admin/expert homepage



@thomashaile can you list them here => [2. Create wireframes](https://github.com/MesutBE/Driving-Licence-App/issues/5)

We can talk about wireframes in `2. Create wireframes` issue

**Comment by MesutBE** [comment]
> https://www.youtube.com/watch?v=HPIjjFGYSJ4 -react, nodejs, with mysql db
> https://www.youtube.com/watch?v=4CeTFW4agRw. -react form validation

@thomashaile What is your results from the videos? Can you share us?

**Comment by thomashaile** [comment]
in the video he is showing us using mysql with react and nodejs in very clear and easy way. but when i see our project that we forked from you/evan there is db folder and want us to do using sqllite.

**Comment by MesutBE** [comment]
You are right. I realized that.
The second video seems about creating a registration page.

**Comment by MesutBE** [comment]
> some notes & questions:
> test-id should be test_id
> what do you mean ‘marksperanswer’ ?
> why do we need 'created_on' for the test?
> in the questions table I add 'option_description' column.. because some answers has a explanation?
> in options table do we need question_id?
> what do you mean by option_number?

Let's find out the answers and then come to end of the database?

**Comment by thomashaile** [comment]
sqllite is better we already working on it and on the backend using nodejs. i will share it later...

**Comment by feridunAKYOL** [comment]
but the question is not about it? about the schema...
and we are waiting for the rest of the sqlite database about users

**Comment by thomashaile** [comment]
Ok, let me share what i did on the back end then try to access it from
http://localhost:8080/users/

**Comment by thomashaile** [comment]
here is the link for the sqlite db  and back-end using node js i started.

https://github.com/thomashaile/Driving-Licence-App/tree/back-end

**Comment by feridunAKYOL** [comment]
but I think first we should share our task for the backend part...
we decided to the database part firstly.. after combining the data we will check the database then we'll share the backend parts..
otherwise it will not be a group work.. and there may be a chaos.

**Comment by thomashaile** [comment]
yes feredun added only the user and test part to check the database and tables i created.unless i coudnot check it correctly including the connection to the database

**Comment by thomashaile** [comment]
> but I think first we should share our task for the backend part...
> we decided to the database part firstly.. after combining the data we will check the database then we'll share the backend parts..
> otherwise it will not be a group work.. and there may be a chaos.

sorry for that i didnot think like that i thought i am arranging the db connection, just lets try to see the db.

**Comment by feridunAKYOL** [comment]
not a problem..to see the database part you are right.. thanks for your work...
if you are ready we can think about what we will do this week for the backend.. functions etc..

**Comment by MesutBE** [comment]
![Driving_Licence_WebWinners](https://user-images.githubusercontent.com/59531743/87734481-04285380-c7d3-11ea-8450-6ebcd989f0af.png)

**Comment by MesutBE** [comment]
![Driving_Licence_WebWinners(1)](https://user-images.githubusercontent.com/59531743/87838245-a65d3f80-c896-11ea-9d85-8ffb8a17142c.png)

**Comment by MesutBE** [comment]
![Driving_Licence_WebWinners(2)](https://user-images.githubusercontent.com/59531743/87900097-9b9bd980-ca53-11ea-807e-8e5e92808c59.png)
